
services:
  # Aplicação Streamlit conectada ao Neon
  streamlit-app:
    build: .
    container_name: dolartracker_app
    ports:
      - "8502:8501"
    environment:
      DATABASE_URL: ${DATABASE_URL:-}
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        echo 'Banco pronto!'
        python -c "from config.database import create_tables; create_tables()"
        python -c "from scripts.etl import load_data; load_data()" &
        exec streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0