# render.yaml
# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: dolartracker-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BCB_API_URL
        value: https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados
